# Generated by Django 4.0.5 on 2022-06-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details_of_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('publisher_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
