# Generated by Django 4.0.5 on 2022-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_alter_details_of_book_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_of_book',
            name='email_id',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
